# Generated by Django 3.0.4 on 2021-03-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peoplemessages',
            name='email',
            field=models.EmailField(blank=True, default='no_id@xyz', max_length=254),
        ),
    ]
